# Configuration for the cfp_data_analysis project

scheduler: greedy

split_download:
  start_date: "20230101"
  end_date: "20241231"

integration:
  start_date: "20230101"
  end_date: "20241231"

data_types: ["prices", "load_forecast", "load_actual", "vre", "generation", "crossborder"]
